### ISSUE TITLE
Midas Protocol

### ISSUE THREAD

**Issue by cosmicanon** [kuldeep23907/Ethereum-Lottery-Dapp-Using-Boilerplate#5]
Heya, I saw your repo on Github. Would you be interested in building an idea that has lottery dynamics? Maybe it aligns with what you're doing? It will be a piece of a larger puzzle.

If you're interested in finding out more, please consider joining our Discord and we can chat about it: https://discord.gg/WEMhh8dhqF

Thanks

CosmicAnon
Value Labs

**Comment by kuldeep23907** [comment]
Hi there,

Is the idea using blockchain only?

**Comment by kuldeep23907** [comment]
What i did here is a very basic stuff.

**Comment by kuldeep23907** [comment]
@cosmicanon

**Comment by cosmicanon** [comment]
Heya yep its blockchain..even though you did some "basic stuff" I think its a good start that could be modded a bit to create something that others could buidl upon

**Comment by kuldeep23907** [comment]
Okay then... let me join the discord channel
